### ISSUE TITLE
Tela de login

### ISSUE THREAD

**Issue by Perkles** [codered-co/classifica-me-app#15]
Criar o design da tela de login. 
Durante o processo da mesma irá ser colocado em prática a criação de uma paleta de cores a ser adotada no app tal como fontes.

**Comment by Perkles** [comment]
Sugestão de re-design da tela de login :

![redesign](https://user-images.githubusercontent.com/18516908/63230509-f5f93e00-c1e3-11e9-9abe-76d48c08c16d.jpeg)

Aberto a sugestões e críticas

**Comment by gussouzauni** [comment]
Ótimo! Após finalizar, implementaremos;

**Comment by gussouzauni** [comment]
@ivanvoliveira fecha essa issue aqui quando subir

**Comment by ivanvoliveira** [comment]
@gussouzauni pode deixar!

**Comment by ivanvoliveira** [comment]
Mudanças feitas na Issue #41
